import { useRef, useState } from 'react'
import { useRouter } from 'next/router'
import Image from 'next/image'
import Head from 'next/head'

import Header from '../components/Header'

import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid'
import Footer from '../components/Footer'

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)
  const [searchState, setSearchState] = useState('')

  const search = (e) => {
    e.preventDefault()
    const term = searchInputRef.current.value
    if (!term.trim()) return

    router.push(`/search?term=${term.trim()}`)
  }

  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header />

      {/* Body */}
      <form className='flex flex-col items-center mt-40'>
        <Image
          width='300'
          height='100'
          objectFit='cover'
          src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png'
          alt='Google Logo'
        />
        <div className='flex w-full max-w-[90%] mt-5 justify-center items-center border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full sm:max-w-screen-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 text-gray-500 mr-3' />
          <input
            ref={searchInputRef}
            className='flex-grow focus:outline-none'
            type='text'
          />
          <MicrophoneIcon className='h-5' />
        </div>
        <div className='flex flex-col sm:flex-row w-1/2 space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center'>
          <button className='btn' onClick={search}>
            Google Search
          </button>
          <button className='btn'>I'm Feeling Lucky</button>
        </div>
      </form>

      {/* footer */}
      <Footer />
    </div>
  )
}
